version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/code/backend
      - ./main.py:/code/main.py
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/code/frontend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Exponieren Sie Port 80 für den Zugriff auf NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend